### ISSUE TITLE
Install Instructions Scratch

### ISSUE THREAD

**Issue by nodered** [JarbasAl/fallback-node-red#1]
---updated---

I guess we need some help testing the install instructions, this is starting point

Installing the Node-Red Fallback Skill, Node-Red and the Sample Flow

---

Install the Node-Red Fallback Skill

For the Mark 1
sudo apt-get install libssl-dev libffi-dev
sudo msm install https://github.com/JarbasAl/fallback-node-red
sudo service mycroft-skills restart

For Picroft
sudo apt-get install libssl-dev libffi-dev
sudo msm install https://github.com/JarbasAl/fallback-node-red
sudo service mycroft-skills restart

For desktop Mycroft dev installations
cd /home/username/mycroft-core/msm
./msm install https://github.com/JarbasAl/fallback-node-red
./msm update

---

Install Node-Red

Official Node-Red install instructions https://nodered.org/docs/hardware/raspberrypi

bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)

If on a Raspberry Pi, choose Pi specific install, this limits the max amount of memory to 256MB in the case a poorly configured flow

sudo systemctl enable nodered.service

 This will automatically start node-red at boot time

sudo service nodered start

This starts Node-Red, check to see if it's running at http://127.0.0.1:1880 / http://mycroftaddress:1880 ...If you have a firewall, open port 1880

---

Importing the Sample Flow

Go to https://raw.githubusercontent.com/JarbasAl/fallback-node-red/master/sample_flow.txt
Copy the JSON text
Go to http://addressofmycroft:1880
In the upper righthand corner menu, choose... Import > Clipboard
This will open the "Import nodes" window
Paste in the contents from the sample_flow.txt
Click on Import and the flow should appear
Click on the workspace to place the flow
Click on Deploy in the upper-right

Next click on Deploy
After you deploy, the websocket nodes should say 'connected' if the the fallback
skill was installed properly
Check the 'intent' node to see what key words are being used to trigger a skill
Go to the Mycroft terminal to test the intents

**Comment by penrods** [comment]
Two minor tweaks to what was written above for instructions:


Importing the Sample Flow

Go to **https://raw.githubusercontent.com/JarbasAl/fallback-node-red/master/sample_flow.txt**
Copy the JSON text
Go to http://addressofmycroft:1880
In the upper righthand corner menu, choose... Import > Clipboard
This will open the "Import nodes" window
Paste in the contents from the sample_flow.txt
Click on Import and the flow should appear
**Click on the workspace to place the flow**
**Click on Deploy in the upper-right**
