### ISSUE TITLE
Picroft Install failing

### ISSUE THREAD

**Issue by ScottJWalter** [JarbasAl/fallback-node-red#4]
Working with the latest version of Mycroft-core (10.2.10) on a Raspi 3B.  Node red installs fine, however trying to install the skill:

`pi@picroft:~ $ sudo msm install https://github.com/JarbasAl/fallback-node-red`

produces the following:

`Traceback (most recent call last):`
`  File "/usr/local/bin/msm", line 9, in <module>`
`    load_entry_point('msm==0.5.14', 'console_scripts', 'msm')()`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point`
`    return get_distribution(dist).load_entry_point(group, name)`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point`
`    return ep.load()`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load`
`    ['__name__'])`
`  File "/usr/local/lib/python2.7/dist-packages/msm/__init__.py", line 22, in <module>`
`    from .exceptions import *`
`  File "/usr/local/lib/python2.7/dist-packages/msm/exceptions.py", line 24, in <module>`
`    from future.utils import raise_from`
`ImportError: No module named future.utils`

**Comment by nodered** [comment]
Try this assuming your in the /home/pi directory...
```source mycroft-core/.venv/bin/activate```
```sudo mycroft-core/.venv/bin/msm install https://github.com/JarbasAl/fallback-node-red```
```sudo chown pi -R /opt/mycroft/skills/fallback-node-red.jarbasal/```

**Comment by wmurray-es** [comment]
https://github.com/JarbasAl/fallback-node-red/issues/4#issuecomment-441473796

Same error here after trying your suggestion @nodered
