### ISSUE TITLE
Error loading skill on Linux Mycroft

### ISSUE THREAD

**Issue by brezuicabogdan** [JarbasAl/fallback-node-red#5]
Hi,

I successfully installed the skill but when Mycroft tryes to load the skill I get this error

```
17:49:47.639 - mycroft.skills.core:load_skill:119 - INFO - ATTEMPTING TO LOAD SKILL: fallback-node-red.jarbasal with ID fallback-node-red.jarbasal
~~~~.skills.core:default_shutdown:1453 - ERROR - Skill specific shutdown function encountered an error: RuntimeError('cannot join thread before it is started',)
17:49:52.812 - mycroft.skills.core:load_skill:166 - ERROR - Failed to load skill: fallback-node-red.jarbasal
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/core.py", line 146, in load_skill
    raise e
  File "/opt/mycroft-core/mycroft/skills/core.py", line 142, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/fallback-node-red.jarbasal/__init__.py", line 97, in initialize
    self.factory.bind(self.emitter)
AttributeError: 'NodeRedSkill' object has no attribute 'emitter'
```

actually there are 2 errors in there but I think the shutdown one is not important.

If you need more information on my particular installation please let me know.

Thank you.

**Comment by JarbasAl** [comment]
emitter has been deprecated in latest mycroft core, should be an easy fix

just change self.emitter to self.bus

will make a fix soon, thx for the heads up

**Comment by brezuicabogdan** [comment]
My pleasure - thanks for the skill it is the start of exactly what I want to implement.

Will attempt the self.bus change and let you know

**Comment by brezuicabogdan** [comment]
The replacement you suggested did the trick for now. Waiting for the update.
Thanks.

**Comment by JarbasAl** [comment]
skill still needs a cleanup, but added a workaround for now
