### ISSUE TITLE
Any way to connect remotely ?

### ISSUE THREAD

**Issue by cooljimy84** [JarbasAl/fallback-node-red#7]
I have a Mark1 and want to have this functionally, but nodered is running on my server, not on the mark1, is there any way to get this working like that ? (i've looked and can't see port 6789 listening on the network, i assume it's just listening on the loopback)

**Comment by JarbasAl** [comment]
node red starts the connection to mycroft, it can be running anywhere

you will need to set the firewall permissions in a mark1

```ufw allow 6789```

NOTE: this is not the port of the mycroft messagebus!
